#server:
#  port: 8098
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:10086/eureka
#    register-with-eureka: true
#    fetch-registry: true
#spring:
#  application:
#    name: integral-backstage
